# Generated by Django 3.1 on 2020-08-25 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_debt'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='debt_grps',
            field=models.CharField(default='{}', max_length=1000),
        ),
    ]
