# Generated by Django 3.1 on 2020-08-24 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheet', '0003_auto_20200824_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledger',
            name='group',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
