# Generated by Django 3.1 on 2020-08-24 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheet', '0008_auto_20200824_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledger',
            name='amount',
            field=models.FloatField(null=True),
        ),
    ]
