# Generated by Django 3.1 on 2020-08-24 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheet', '0009_auto_20200824_1845'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledger',
            name='group',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ledger',
            name='amount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='ledger',
            name='borrower',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='ledger',
            name='lender',
            field=models.CharField(default='', max_length=500),
        ),
    ]
