# Generated by Django 3.1 on 2020-08-25 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sheet', '0010_auto_20200824_1850'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ledger',
            old_name='group',
            new_name='grp',
        ),
    ]
