# Generated by Django 3.1 on 2020-08-25 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheet', '0011_auto_20200825_0508'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledger',
            name='desc',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='ledger',
            name='borrower',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='ledger',
            name='lender',
            field=models.CharField(default='', max_length=100),
        ),
    ]
