# Generated by Django 3.1 on 2020-08-25 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheet', '0012_auto_20200825_0527'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lender', models.CharField(default='', max_length=100)),
                ('borrower', models.CharField(default='', max_length=100)),
                ('amount', models.CharField(default='', max_length=100)),
                ('grp_name', models.CharField(max_length=100, null=True)),
                ('desc', models.CharField(max_length=500, null=True)),
            ],
        ),
    ]
