# Generated by Django 3.1 on 2020-08-25 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheet', '0013_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='group',
            name='borrower',
        ),
        migrations.RemoveField(
            model_name='group',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='group',
            name='lender',
        ),
        migrations.AddField(
            model_name='group',
            name='amounts',
            field=models.CharField(default='[]', max_length=100),
        ),
        migrations.AddField(
            model_name='group',
            name='borrowers',
            field=models.CharField(default='[]', max_length=100),
        ),
        migrations.AddField(
            model_name='group',
            name='descs',
            field=models.CharField(default='[]', max_length=500),
        ),
        migrations.AddField(
            model_name='group',
            name='lenders',
            field=models.CharField(default='[]', max_length=100),
        ),
    ]
