# Generated by Django 3.1 on 2020-08-25 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheet', '0014_auto_20200825_0904'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='pk_vals',
            field=models.CharField(default='[]', max_length=500),
        ),
    ]
