# Generated by Django 3.1 on 2020-08-25 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sheet', '0015_group_pk_vals'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='amounts',
        ),
        migrations.RemoveField(
            model_name='group',
            name='borrowers',
        ),
        migrations.RemoveField(
            model_name='group',
            name='descs',
        ),
        migrations.RemoveField(
            model_name='group',
            name='lenders',
        ),
    ]
